version: "3.7"

services:
  app:
    build: .
    ports:
      - "5555:5000"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis_data:/data

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
